import express from 'express';import bcrypt from 'bcryptjs';import {z} from 'zod';import {User,KitModel} from './models';import {signUser,verifyUser} from '../lib/auth';import {buildKit} from './pipeline';
export const router=express.Router();
function auth(req:any,res:any,next:any){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Unauthorized'});req.user=verifyUser(h.slice(7));next()}catch{return res.status(401).json({error:'Invalid session'})}}
router.post('/auth/register',async(req,res)=>{try{const {email,password}=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);if(await User.findOne({email}))return res.status(409).json({error:'Email already registered'});const u=await User.create({email,passwordHash:await bcrypt.hash(password,12)});res.json({token:signUser(String(u._id)),email})}catch(e:any){res.status(400).json({error:e.message})}});
router.post('/auth/login',async(req,res)=>{try{const {email,password}=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const u:any=await User.findOne({email});if(!u||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({error:'Invalid credentials'});res.json({token:signUser(String(u._id)),email})}catch(e:any){res.status(400).json({error:e.message})}});
router.get('/kits',auth,async(req:any,res)=>{res.json(await KitModel.find({userId:req.user.id}).sort({createdAt:-1}).lean())});
router.get('/kits/:id',auth,async(req:any,res)=>{const k=await KitModel.findOne({_id:req.params.id,userId:req.user.id}).lean();if(!k)return res.status(404).json({error:'Kit not found'});res.json(k)});
router.post('/kits',auth,async(req:any,res)=>{try{const {jd,companyUrl,days}=z.object({jd:z.string().min(20),companyUrl:z.string().url(),days:z.number().int().min(1).max(60)}).parse(req.body);const kit=await buildKit(jd,companyUrl,days);const saved=await KitModel.create({userId:req.user.id,name:kit.role.title||kit.source.company,kit});res.status(201).json(saved)}catch(e:any){res.status(400).json({error:e.message})}});
router.put('/kits/:id',auth,async(req:any,res)=>{const k=await KitModel.findOneAndUpdate({_id:req.params.id,userId:req.user.id},{$set:{kit:req.body.kit,name:req.body.name}},{new:true}).lean();if(!k)return res.status(404).json({error:'Kit not found'});res.json(k)});
router.delete('/kits/:id',auth,async(req:any,res)=>{await KitModel.deleteOne({_id:req.params.id,userId:req.user.id});res.json({ok:true})});
router.post('/kits/:id/regenerate',auth,async(req:any,res)=>{try{const old:any=await KitModel.findOne({_id:req.params.id,userId:req.user.id});if(!old)return res.status(404).json({error:'Kit not found'});const section=req.body.section;const base=old.kit as any;if(section==='schedule'){base.schedule=require('../lib/schedule').allocateSchedule(base.role.requirements,base.questions,base.schedule.days_available)}else if(section==='questions'){const fresh=await require('./llm').generateQuestions(base.role.requirements,JSON.stringify(base.company_brief));const edited=(base.questions||[]).filter((q:any)=>q.state==='edited'||q.state==='pinned');base.questions=[...edited,...fresh.map((q:any,i:number)=>({...q,id:`qregen-${Date.now()}-${i}`,state:'generated'}))]}else if(section==='flashcards'){const fresh=await require('./llm').generateFlashcards(base.role.requirements,base.questions);const edited=(base.flashcards||[]).filter((f:any)=>f.state==='edited'||f.state==='pinned');base.flashcards=[...edited,...fresh.map((f:any,i:number)=>({...f,id:`fregen-${Date.now()}-${i}`,state:'generated'}))]}else if(section==='company_brief'){base.company_brief=await require('./llm').generateBrief(base.source.company,JSON.stringify(base.source.pages_used),JSON.stringify(base.company_brief))}else return res.status(400).json({error:'Unsupported section'});old.kit=base;await old.save();res.json(old)}catch(e:any){res.status(400).json({error:e.message})}});
router.patch('/kits/:id/practice',auth,async(req:any,res)=>{const k:any=await KitModel.findOne({_id:req.params.id,userId:req.user.id});if(!k)return res.status(404).json({error:'Kit not found'});k.practice={...(k.practice||{}),[req.body.flashcardId]:{confidence:req.body.confidence,at:new Date().toISOString()}};await k.save();res.json(k.practice)});
