import { Kit, Requirement, Question } from '../lib/types';
import {crawl,publicInterviewResearch} from './retrieval'; import {extractJD,generateQuestions,generateGapQuestions,generateBrief,generateFlashcards} from './llm'; import {uncovered} from '../lib/coverage'; import {allocateSchedule} from '../lib/schedule'; import {validateKit} from '../lib/validation';
export async function buildKit(jd:string,companyUrl:string,days:number):Promise<Kit>{
 const extracted=await extractJD(jd); const pages=await crawl(companyUrl); const publicResearch=await publicInterviewResearch(extracted.company||new URL(companyUrl).hostname); const pageText=pages.map(p=>`URL:${p.url}\nTITLE:${p.title}\n${p.text}`).join('\n\n');
 const brief=await generateBrief(extracted.company||new URL(companyUrl).hostname,pageText,publicResearch.text);
 const qs0=await generateQuestions(extracted.requirements,`${pageText}\n${publicResearch.text}`); let qs=qs0.map((q,i)=>({...q,id:q.id||`q${i+1}`,state:'generated' as const})); let pass=1;
 for(let i=0;i<2;i++){const gapIds=uncovered(extracted.requirements,qs);if(!gapIds.length)break;pass++;const gaps=extracted.requirements.filter(r=>gapIds.includes(r.id));const more=await generateGapQuestions(gaps,`${pageText}\n${publicResearch.text}`);qs.push(...more.map((q,j)=>({...q,id:`q${qs.length+j+1}`,state:'generated' as const})));}
 const flash=await generateFlashcards(extracted.requirements,qs); const kit:Kit={source:{company:extracted.company||new URL(companyUrl).hostname,company_url:companyUrl,role:extracted.role||'',location:extracted.location||'',jd_chars:jd.length,researched_at:new Date().toISOString(),pages_used:pages.map(p=>p.url)},company_brief:brief,role:{title:extracted.role||'',seniority:extracted.seniority||'',responsibilities:extracted.responsibilities||[],requirements:extracted.requirements},questions:qs,flashcards:flash.map((f,i)=>({...f,id:f.id||`f${i+1}`,state:'generated' as const})),schedule:allocateSchedule(extracted.requirements,qs,days),coverage:{uncovered_requirement_ids:uncovered(extracted.requirements,qs),passes:pass}};
 const errors=validateKit(kit);if(errors.length)throw new Error(`Generated kit validation failed: ${errors.join('; ')}`);return kit;
}
