import * as cheerio from 'cheerio';
import dns from 'node:dns/promises';
import net from 'node:net';
const MAX=350000;
function privateIp(ip:string){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168} return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80')}
async function safe(url:string){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('Only HTTP(S) URLs are allowed');const addrs=await dns.lookup(u.hostname,{all:true});if(addrs.some(a=>privateIp(a.address)) && process.env.ALLOW_LOCAL_URLS!=='true')throw new Error('Private or loopback address rejected');return u}
export async function fetchPage(url:string){const u=await safe(url);const r=await fetch(u,{redirect:'follow',signal:AbortSignal.timeout(12000),headers:{'user-agent':'AI-Interview-Prep/1.0'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const type=r.headers.get('content-type')||'';if(!type.includes('text/html')&&!type.includes('text/plain'))throw new Error('Unsupported content type');const text=(await r.text()).slice(0,MAX);const $=cheerio.load(text);$('script,style,noscript,svg').remove();const links:string[]=[];$('a[href]').each((_,e)=>{try{const h=new URL($(e).attr('href')!,u).href;if(h.startsWith(u.origin)&&!links.includes(h))links.push(h)}catch{}});return {url:u.href,title:$('title').text().trim(),text:$.root().text().replace(/\s+/g,' ').trim(),links:links.slice(0,120)} }
export async function crawl(start:string){const first=await fetchPage(start);const scored=first.links.map(url=>{const s=url.toLowerCase();let score=0;for(const k of ['career','job','hiring','about','engineering','team','culture','interview'])if(s.includes(k))score+=3;return {url,score}}).sort((a,b)=>b.score-a.score).slice(0,8);const pages=[first];for(const x of scored){try{pages.push(await fetchPage(x.url))}catch{}}return pages}
export async function publicInterviewResearch(company:string){const q=encodeURIComponent(`${company} software engineering interview process questions`);const base=process.env.SEARCH_URL?.replace('{query}',q);if(!base)return {text:'No public search endpoint configured.',sources:[]};try{const r=await fetch(base,{signal:AbortSignal.timeout(8000),headers:{'user-agent':'AI-Interview-Prep/1.0'}});const t=(await r.text()).replace(/\s+/g,' ').slice(0,30000);return {text:t,sources:[base]}}catch{return {text:'No reliable public interview discussion could be retrieved.',sources:[]}}}
